name: Lint, Build and Push 
 
on: 
  push: 
    branches: [ main ] 
  pull_request: 
    branches: [ main ] 
 
jobs: 
  lint: 
    name: Run Super-Linter 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v4 
      - name: Run Super-Linter 
        uses: super-linter/super-linter@v6 
        env: 
          VALIDATE_ALL_CODEBASE: true 
          DEFAULT_BRANCH: main 
